### ISSUE TITLE
What about the name?

### ISSUE THREAD

**Issue by nanoni17728** [MegaLoler/LilyBot#2]
I wasn’t sure it would have been appropriate to comment in #1 so I’m opening a new issue just in case!

I’ve been meaning to work on my own fork of  LilyBot, and I wondered if I had to go with a slightly modified name or a new name altogether.

Thanks for your time!

**Comment by MegaLoler** [comment]
It's okay! I don't mind if you reuse the name or use a different one, it's up to you!

**Comment by nanoni17728** [comment]
Alright, thanks!
